import { Link } from 'react-router-dom';
import { useState } from 'react';
import { Header } from '../components/Header';
import { Card, Button } from '../components/Card';
import { Icon } from '../components/Icon';
import { fitnessData } from '../data/fitness';

export function FitnessPage() { return <><Header title="Fitness and activity" subtitle="Move in a way that supports your day" /><main className="page-width space-y-4 py-5"><Card className="overflow-hidden p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-primary-fixed text-primary"><Icon className="text-4xl">fitness_center</Icon></div><div className="flex-1"><span className="section-label">Today's workout</span><h2 className="mt-1 font-headline text-xl font-bold">{fitnessData.today.title}</h2><p className="mt-1 font-body text-sm text-on-surface-variant">{fitnessData.today.duration} · {fitnessData.today.intensity} intensity · {fitnessData.today.exercises} exercises</p></div><Link to="/fitness/workout"><Button>Start workout <Icon>arrow_forward</Icon></Button></Link></div></Card><div className="flex items-center justify-between"><h2 className="font-headline text-xl font-bold">Recommended for you</h2><Link to="/progress" className="font-body text-xs font-bold text-primary">View progress</Link></div>{fitnessData.recommendations.map(item => <Card key={item.title} className="flex items-center gap-4 p-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-tertiary-fixed/50 text-tertiary"><Icon>{item.icon}</Icon></span><div className="flex-1"><strong className="block font-body text-sm">{item.title}</strong><span className="font-body text-xs text-on-surface-variant">{item.detail}</span></div><span className="font-body text-xs font-bold text-outline">{item.duration}</span></Card>)}</main></>; }
export function WorkoutPage() { const [started, setStarted] = useState(false); return <><Header title="Active workout" subtitle="Full Body Foundation" /><main className="page-width py-5"><Card className="p-5"><div className="mb-6 flex items-center justify-between"><div><span className="section-label">Session 01</span><h1 className="mt-1 font-headline text-2xl font-bold">Full Body Foundation</h1></div><span className="rounded-full bg-secondary-fixed/50 px-3 py-1 font-body text-xs font-bold text-secondary">25 min</span></div><div className="flex aspect-video items-center justify-center rounded-3xl bg-primary-fixed/20 text-primary"><Icon className="text-6xl">directions_run</Icon></div><div className="mt-5 flex items-center justify-between rounded-2xl bg-surface-container-low p-4"><div><span className="section-label">Current exercise</span><strong className="mt-1 block font-headline">{started ? 'Bodyweight squats' : 'Ready when you are'}</strong></div><Button onClick={() => setStarted(true)}>{started ? 'In progress' : 'Begin'} <Icon>{started ? 'pause' : 'play_arrow'}</Icon></Button></div></Card></main></>; }
