import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Button } from '../components/Card';
import { Icon } from '../components/Icon';
import { SelectionCard } from '../components/SelectionCard';
import { ProgressBar } from '../components/ProgressBar';

const steps = [{ title: 'Tell us about you', choices: [['female', 'Female'], ['male', 'Male'], ['transgender', 'Non-binary']] }, { title: 'What is your main goal?', choices: [['track_changes', 'Lose weight'], ['fitness_center', 'Gain muscle'], ['favorite', 'Improve fitness'], ['restaurant', 'Eat healthier']] }, { title: 'How active are you?', choices: [['chair', 'Sedentary'], ['directions_walk', 'Lightly active'], ['directions_run', 'Moderately active'], ['bolt', 'Very active']] }, { title: 'Choose your diet preference', choices: [['spa', 'Vegetarian'], ['restaurant', 'Non-vegetarian'], ['eco', 'Vegan'], ['tune', 'Flexible']] }];
export function OnboardingPage() { const navigate = useNavigate(); const [step, setStep] = useState(0); const [selected, setSelected] = useState(''); const [name, setName] = useState('Alex'); const current = steps[step]; const next = () => { if (step === steps.length - 1) navigate('/dashboard'); else { setStep(value => value + 1); setSelected(''); } }; return <main className="min-h-screen bg-surface px-4 py-6"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-md flex-col"><header className="mb-8 flex items-center justify-between"><Link to="/signin" className="flex items-center gap-2 font-headline font-bold text-primary"><Icon filled>spa</Icon> BealthAI</Link><span className="section-label">Personal calibration</span></header>{step === 0 && <label className="mb-6 block"><span className="section-label mb-2 block">What should we call you?</span><input value={name} onChange={event => setName(event.target.value)} className="w-full rounded-xl border border-outline-variant/50 bg-surface-container-lowest px-4 py-3 font-body outline-none focus:border-primary" /></label>}<div className="mb-8"><div className="mb-2 flex items-center justify-between"><span className="section-label">Step {step + 1} of {steps.length}</span><span className="font-body text-xs text-outline">Longevity path</span></div><ProgressBar value={((step + 1) / steps.length) * 100} /></div><div className="flex-1"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary-fixed text-primary"><Icon>vital_signs</Icon></div><h1 className="font-headline text-2xl font-bold">{step === 0 ? `Nice to meet you, ${name}` : current.title}</h1><p className="mt-2 font-body text-sm leading-6 text-on-surface-variant">These preferences help shape a more useful daily plan. You can change them later.</p><div className="mt-6 space-y-3">{current.choices.map(([icon, label]) => <SelectionCard key={label} icon={icon} label={label} selected={selected === label} onClick={() => setSelected(label)} />)}</div></div><div className="mt-8 flex gap-3"><Button type="button" variant="secondary" onClick={() => step ? setStep(value => value - 1) : navigate('/signin')} className="flex-1"><Icon>arrow_back</Icon> Back</Button><Button type="button" onClick={next} className="flex-1">{step === steps.length - 1 ? 'Finish' : 'Continue'} <Icon>arrow_forward</Icon></Button></div></div></main>; }
